# starship prompt manager config file

[status]
symbol = ""
disabled = false

[python]
format = '[${symbol}${pyenv_prefix}${version}( \($virtualenv\))]($style) '
symbol = "ğŸ "

[nix_shell]
format = '[$symbol$state($name)]($style) '
symbol = "â„ï¸ "
impure_msg = ""

[package]
format = "[$symbol$version]($style) "
symbol = "ğŸ“¦ "

[rust]
format = "[$symbol$version]($style) "
symbol = "ğŸ¦€ "
#symbol = "â“‡ "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "î‚ "

[battery]
disabled = true
